#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        iframe_sniffer:
            enable: true
            category: "Misc"
            name: "iFrame Sniffer"
            description: "This module attempts to do framesniffing (aka Leaky Frame).  It will append leakyframe.js (written by Paul Stone) to the DOM and check for specified anchors to be present on a URL.<br />For more information, refer to <a href='https://www.contextis.com/en/blog/framesniffing-against-sharepoint-and-linkedin'>https://www.contextis.com/en/blog/framesniffing-against-sharepoint-and-linkedin</a>"
            authors: ["Bart Leppens"]
            target:
                working: ["S", "IE"]
                not_working: ["ALL"]
