#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        simple_hijacker:
            enable: true
            category: "Social Engineering"
            name: "Simple Hijacker"
            description: "Hijack clicks on links to display what you want."
            templates: ["credential", "confirmbox", "amazon", "chromecertbeggar", "chromecertbeggar2"]
            authors: ["gallypette"]
            target:
                user_notify: ['ALL']
