#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    extension:
        dns:
            enable: false
            name: 'DNS Server'
            authors: ['soh_cah_toa']
            protocol: 'udp'
            address: '127.0.0.1'
            port: 5300
            upstream: [
                ['udp', '8.8.8.8', 53],
                ['tcp', '8.8.8.8', 53]
            ]
