#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
# References:
# https://www.exploit-db.com/exploits/40373/
#
beef:
    module:
        asus_dslx11_dns_hijack:
            enable: true
            category: ["Exploits", "Router"]
            name: "ASUS DSL-X11 ADSL Router DNS Hijack"
            description: "Attempts to change the DNS setting on a ASUS DSL-X11 ADSL router.<br/><br/>This router reportedly does not require authentication to change the DNS servers.<br/><br/>This module has not been tested."
            authors: ["Todor Donev"]
            target:
                unknown: ["ALL"]
