#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        test_get_variable:
            enable: true
            category: "Debug"
            name: "Test JS variable passing"
            description: "Test for JS variable passing from another BeEF's script via Window object"
            authors: ["dnkolegov"]
            target:
                 working: ["All"]
