#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        f5_bigip_cookie_stealing:
            enable: true
            category: ["Network","ADC"]
            name: "F5 BigIP User's Cookie Stealing"
            description: "This module retrieves all BigIP user's session cookies, bypassing sandbox restrictions."
            authors: ["dnkolegov, ovbroslavsky, neoleksov"]
            target:
                working: ["ALL"]
