#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        dlink_dir_615_csrf:
            enable: true
            category: ["Exploits", "Router"]
            name: "D-Link DIR-615 Password Wipe"
            description: "Attempts to enable remote administration on port 8080 and change the admin password on a D-Link DIR-615 router."
            authors: ["antisnatchor", "n0x00"]
            target:
                working: ["ALL"]
