#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        test_beef_debug:
            enable: true
            category: "Debug"
            name: "Test beef.debug()"
            description: "Test the 'beef.debug()' function. This function wraps 'console.log()'"
            authors: ["bcoles"]
            target:
                 working: ["All"]
                 not_working: ["IE"]
