#
<<<<<<< HEAD
# Copyright (c) 2006-2026 Wade Alcorn - wade@bindshell.net
=======
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
>>>>>>> c308392cb3a7bf9025c661931b553d9835aacdcb
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        ping_sweep_ff:
            enable: true
            category: "Network"
            name: "Ping Sweep (FF)"
            description: "Discover active hosts in the internal network of the hooked browser. It works by calling a Java method from JavaScript and does not require user interaction.<br> For browsers other than Firefox, use the 'Ping Sweep (Java)' module."
            authors: ["jgaliana"]
            target:
                working: ["FF"]
                not_working: ["C", "S", "O", "IE"]
